<a href="https://colab.research.google.com/github/SoumyaTeotia/Pytorch-Tutorials/blob/main/00_pyTorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Practice

In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.0.1+cu118


In [ ]:
#scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
#scalar dimension
scalar.ndim

0

In [ ]:
#Get tensor back as Python int
scalar.item()

7

In [ ]:
#vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [ ]:
#no. of dimension = no. of square brackets
vector.ndim

1

In [ ]:
#total no. of elements = size of tensor * dimension of tensor
vector.shape

torch.Size([2])

In [ ]:
#MATRIX
MATRIX = torch.tensor([[7,8], [9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [ ]:
MATRIX.ndim

2

In [ ]:
MATRIX[0]

tensor([7, 8])

In [ ]:
MATRIX.shape #here 2x2

torch.Size([2, 2])

In [ ]:
#TENSOR
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [ ]:
TENSOR.ndim

3

In [ ]:
TENSOR.shape #we've got one 3x3 shaped tensor (i.e. the first sq. bracket)

torch.Size([1, 3, 3])

In [ ]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

###Random Tensors

In [ ]:
#create a random tensor of size (3, 4)
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.3926, 0.7503, 0.4980, 0.3810],
        [0.8276, 0.0438, 0.8832, 0.3748],
        [0.6152, 0.2393, 0.9769, 0.2511]])

In [ ]:
random_tensor.ndim

2

In [ ]:
#create a random tensor with similar shape to an image tensor
random_image_tensor = torch.rand(size=(224, 224, 3)) #height, width, colour channels (R,G,B)
random_image_tensor.shape, random_image_tensor.ndim

(torch.Size([224, 224, 3]), 3)

###Zeros and Ones

In [ ]:
#Create a tensor of all zeros
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
zeros*random_tensor #zeros created if you want to remove some specific rows/columns of the tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
#Create a tensor of all ones
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
ones.dtype #default data type

torch.float32

###Creating a range of tensors and tensors-like

In [ ]:
#use torch.range() and get deprecated message, use torch.arange()
torch.arange(0,10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
one_to_thousand = torch.arange(start=1, end=1000, step=7)
one_to_thousand

tensor([  1,   8,  15,  22,  29,  36,  43,  50,  57,  64,  71,  78,  85,  92,
         99, 106, 113, 120, 127, 134, 141, 148, 155, 162, 169, 176, 183, 190,
        197, 204, 211, 218, 225, 232, 239, 246, 253, 260, 267, 274, 281, 288,
        295, 302, 309, 316, 323, 330, 337, 344, 351, 358, 365, 372, 379, 386,
        393, 400, 407, 414, 421, 428, 435, 442, 449, 456, 463, 470, 477, 484,
        491, 498, 505, 512, 519, 526, 533, 540, 547, 554, 561, 568, 575, 582,
        589, 596, 603, 610, 617, 624, 631, 638, 645, 652, 659, 666, 673, 680,
        687, 694, 701, 708, 715, 722, 729, 736, 743, 750, 757, 764, 771, 778,
        785, 792, 799, 806, 813, 820, 827, 834, 841, 848, 855, 862, 869, 876,
        883, 890, 897, 904, 911, 918, 925, 932, 939, 946, 953, 960, 967, 974,
        981, 988, 995])

In [ ]:
one_to_ten = torch.arange(start=1, end=11, step=1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
#Creating tensors like
ten_zeros = torch.zeros_like(input = one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

###Tensor Datatypes
**Note**: Tensor datatype is one of the 3 big errors you'll run into with PyTorch & deep learning:
1. Tensors not right datatypes (when on a data type, you are applying operations of a different datatype)
2. Tensors not right shape (during matrix multiplication)
3. Tensors not on the right device (doing operations on two tensors, where one is on CPU(by default) and the other in on another device like GPU(cuda))

In [ ]:
#Float 32 tensor
#Lesser bit => lesser precision => lesser space => Faster calculation
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, #what datatype is the tensor (e.g. float 32 or float16)
                               device=None, #what device is your tensor on, if GPU then mention as "cuda"
                               requires_grad=False) #whether or not to track gradients with this tensors operations
float_32_tensor

tensor([3., 6., 9.])

In [ ]:
float_32_tensor.dtype #When dtype=None then also dtype=float32, since it is the default value

torch.float32

In [ ]:
#Changing Datatype
float_16_tensor = float_32_tensor.type(torch.float16) #or torch.half
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

###Getting information from tensors (tensor attributes)
1. Tensors not right datatypes - to get datatype from a tensor, can use `tensor.dtype`
2. Tensors not right shape - to get shape from a tensor, can use `tensor.shape`(attribute) or `tensor.size()`(function)
3. Tensors not on the right device - to get device from a tensor, can use `tensor.device`

In [ ]:
#Create a tensor
some_tensor = torch.rand(3, 4)
some_tensor

tensor([[0.6603, 0.4760, 0.3109, 0.8061],
        [0.6870, 0.2338, 0.6186, 0.5078],
        [0.4900, 0.3092, 0.4406, 0.8441]])

In [ ]:
#tensor.size() and tensor.shape both give same results, one is a function and the other is an attribute
some_tensor.size(), some_tensor.shape

(torch.Size([3, 4]), torch.Size([3, 4]))

In [ ]:
#Find out details about some tensor
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device tensor is on: {some_tensor.device}")


tensor([[0.6603, 0.4760, 0.3109, 0.8061],
        [0.6870, 0.2338, 0.6186, 0.5078],
        [0.4900, 0.3092, 0.4406, 0.8441]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is on: cpu


###Manipulating Tensors (tensor operations)
Tensor operations include:
* Addition
* Subtraction
* Multilplication (element-wise)
* Division
* Matrix multiplication

Neural networks employ these operations to find patterns in the dataset






In [ ]:
#Create a tensor and add 10 to it
tensor = torch.tensor([1, 2, 3])
tensor+10

tensor([11, 12, 13])

In [ ]:
#Multiply tensor by 10
tensor*10 #tensor value hasn't changed, it changes only when assigned to it

tensor([10, 20, 30])

In [ ]:
#Subtract 10
tensor-10

tensor([-9, -8, -7])

In [ ]:
#Try out PyTorch in-built functions
torch.mul(tensor, 10)

tensor([10, 20, 30])

###Matrix Multiplication
Two main ways of performing multiplication in neural networks and deep learning:
1. Element-wise multiplication
2. Matrix multiplication (dot product)

*@ - matrix multiply*

There are two main rules that performing matrix multiplication needs to satisfy:
1. The **inner dimensions** must match:
* `(3,2) @ (3,2)` won't work
* `(2,3) @ (3,2)` will work
* `(3,2) @ (2,3)` will work

2. The resulting matrix has the shape of the **outer dimensions**:
* `(2,3) @ (3,2)` -> `(2,2)`

In [ ]:
#Element wise multiplication
print(tensor, "*", tensor)
print(f"Equals: {tensor*tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [ ]:
#Matrix Multiplication
torch.matmul(tensor, tensor) #we can do this by applying a for loop, but in-built function of pyTorch are much faster

tensor(14)

In [ ]:
%%time
value=0
for i in range(len(tensor)):
  value+=tensor[i]*tensor[i]
print(value)

tensor(14)
CPU times: user 354 µs, sys: 49 µs, total: 403 µs
Wall time: 410 µs


In [ ]:
%%time
torch.matmul(tensor, tensor) #always use in-built torch functions, except for basic operations

CPU times: user 58 µs, sys: 0 ns, total: 58 µs
Wall time: 61.8 µs


tensor(14)

In [ ]:
#Rule-2
torch.matmul(torch.rand(2,3), torch.rand(3,2))

tensor([[1.2755, 1.2431],
        [0.4028, 0.8770]])

One of the most common errors in deep learning: shape errors

In [ ]:
#Shapes for matrix multiplication
tensor_A = torch.tensor([[1,2],
                         [3,4],
                         [5,6]])
tensor_B = torch.tensor([[7,10],
                         [8,11],
                         [9,12]])
#torch.mm() is a short form of torch.matmul()
#we can't multiply these two tensors as their inner dimensions aren't equal, to resolve this issue we take a transpose of the matrix


To fix our tensor shape issues, we can manipulate the shape of one of our tensors using a **transpose**.

A **transpose** switches the axes or dimensions of a given tensor.

In [ ]:
tensor_B.T

tensor([[ 7,  8,  9],
        [10, 11, 12]])

In [ ]:
torch.matmul(tensor_A, tensor_B.T)

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

##Finding the min, max, mean, sum, etc (tensor aggregation)

In [ ]:
#Create a tensor
x = torch.arange(1, 100, 10)
x

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [ ]:
x.dtype

torch.int64

In [ ]:
#Find the min
torch.min(x), x.min() #any of them can be used

(tensor(1), tensor(1))

In [ ]:
#Find the max
torch.max(x), x.max()

(tensor(91), tensor(91))

In [ ]:
#Find the mean
#The dtype of x is int64 which is long but mean function works on either floating point or complex dtypes.
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(46.), tensor(46.))

In [ ]:
#Find the sum
torch.sum(x), x.sum()

(tensor(460), tensor(460))

##Finding the positional min and max
That is the position at which min and max value exists

In [ ]:
#Find the position in tensor that has the minimum value with argmin() -> returns index position of target tensor where the minimum value occurs
torch.argmin(x)

tensor(0)

In [ ]:
#Finding min value using the index
x[0]

tensor(1)

In [ ]:
#Find the position in tensor that has the maximum value with argmax()
x.argmax()

tensor(9)

In [ ]:
x[9]

tensor(91)

##Reshaping, stacking, squeezing and unsqueezing tensors
* Reshaping - reshapes an input tensor to a defined shape
* View - Return a view of an input tensor of certain shape but keep the same memory as the original tensor (shows the same tensor but from a different perspective)
* Stacking - combine multiple tensors on top of each other (vstack - vertical stack) or side by side (hstack - horizontal stack)
* Squeeze - remove all `1` dimensions from a tensor
* Unsqueeze - add a `1` dimension to a target tensor
* Permute - Return a view of the input with dimensions permuted (swapped) in a certain way


In [ ]:
#Let's create a tensor
y = torch.arange(1., 10.)
y, y.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [ ]:
#RESHAPING - It has to be compatible with the original dimension
#Add an extra dimension
y_reshaped = y.reshape(9,1) #dimensions have to be compatible with the origional dimension, e.g. if we would have used (1,7) then it could take only 7 elements, instead of 9
y_reshaped, y_reshaped.shape

(tensor([[1.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]),
 torch.Size([9, 1]))

In [ ]:
#Change the view
z = y.view(1, 9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
#Changing z changes y (because a view of a tensor shares the same memory as the original tensor)
z[:, 0] = 5 #z[0][0] = 5
z, y

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [ ]:
#Stack tensors on top of each other
y_stacked = torch.stack([y, y, y, y], dim=0) #default dimension = 0
y_stacked

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [ ]:
#torch.squeeze() - removes all single dimensions from a target tensor (if there would've been [1,1,1,9] then it would have given us [9])
y_squeezed = y_reshaped.squeeze()
y_squeezed

tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])

In [ ]:
y_squeezed.shape

torch.Size([9])

In [ ]:
#torch.unsqueeze()
y_unsqueezed = y_squeezed.unsqueeze(dim = 0) #need to mention the dimension
y_unsqueezed

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [ ]:
y_unsqueezed.shape

torch.Size([1, 9])

In [ ]:
#torch.permute - rearranges the dimensions of a target tensorin a specified order
#returns a view of the origional tensor input with its dimensions permuted, viewed from a diff point of view
x_origional = torch.rand(size= (224, 224, 3)) #[height, width, colour_channels]

#Permute the origional tensor to rearrange the axis (or dim) order
x_permuted = x_origional.permute(2,0,1) #shifts axis 0->1, 1->2, 2->0
x_permuted.shape #[colour_channels, height, width]

torch.Size([3, 224, 224])

##Indexing (selecting data from tensors)
Indexing with PyTorch is similar to indexing with NumPy

In [ ]:
#Create a tensor
a = torch.arange(1,10).reshape(1, 3, 3)
a, a.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [ ]:
#Let's index on our new tensor
a[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [ ]:
#Let's index on the middle bracket (dim=1)
a[0][0] #same as a[0, 0]

tensor([1, 2, 3])

In [ ]:
#Let's index on the most inner bracket (last dimension)
a[0][0][0]

tensor(1)

In [ ]:
#You can also use ':' to select "all" of a target dimension
a[:, 0]

tensor([[1, 2, 3]])

In [ ]:
#Get all values of 0th and 1st dimension but onlyt index 1 of 2nd dimension
a[:, :, 1]

tensor([[2, 5, 8]])

In [ ]:
#Get all values of the 0 dimension but only 1 index value of 1st and 2nd dimension
a[:, 1, 1] #gives same output as a[0][1][1] or a[0, 1, 1] except an outer sq. bracket here, this is beacuse of the colon as it is selecting all the elements of dim 0

tensor([5])

In [ ]:
#Get index 0 of 0th and 1st dimension and all values of 2nd dimension
a[0, 0, :] #same as a[0][0]

tensor([1, 2, 3])

In [ ]:
#Index on a to return 9
a[0][2][2]

tensor(9)

In [ ]:
#Index on a to return 3, 6, 9
a[:, :, 2]

tensor([[3, 6, 9]])

###PyTorch tensors &NumPy
NumPy is a popular scientific Python numerical computing library.
And because of this, PyTorch has functionality to interact with it.
* Data in NumPy, want in PyTorch tensor -> `torch.from_numpy(ndarray)`
* PyTorch tensor -> NumPy -> `torch.Tensor.numpy()`

In [ ]:
#NumPy array to tensor
array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array) #warning: when converting from numpy -> pytorch, pytorch reflects numpy's default datatype of float64 unless specified otherwise
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [ ]:
#Changing the value of array doesn't change the value of tensor, as a tensor is created at new memory location
array = array + 1 #adding 1 to all values of array
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [ ]:
#Tensor to NumPy array
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()#In this case numpy reflects pytorch's default datatype of float32
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [ ]:
#Changing the value of tensor doesn't change the value of numpy_tensor
tensor = tensor +1
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

##Reproducibility (Trying to take random out of random)
In short how a neural network learns:
`start with random numbers -> tensor operations -> update random numbers to try and make them better representations of the data -> again -> again -> again...`
To reduce the randomness in neural networks and PyTorch comes the concept of a **random seed**.
Essentially what the random seed does is 'flavour' the randomness.

In [ ]:
import torch
#Create two random tensors
random_tensor_A = torch.rand(3, 4)
random_tensor_B = torch.rand(3, 4)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)

tensor([[0.7032, 0.4071, 0.9536, 0.6827],
        [0.7735, 0.7622, 0.8552, 0.4020],
        [0.6129, 0.3765, 0.4014, 0.3508]])
tensor([[0.8106, 0.2182, 0.3744, 0.8397],
        [0.4764, 0.5529, 0.0604, 0.1845],
        [0.6260, 0.4721, 0.1653, 0.8277]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [ ]:
#Set the random seed
RANDOM_SEED = 42 #set any random value
torch.manual_seed(RANDOM_SEED) # works for only one block of code, so need to rewrite it
random_tensor_C = torch.rand(3, 4)

torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3, 4)

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


##Check for GPU access with PyTorch

In [ ]:
#Check for GPU access with PyTorch
import torch
torch.cuda.is_available()

True

In [ ]:
#Setup device agnostic code
#if GPU is available then it should use it
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [ ]:
#Count no. of devices
torch.cuda.device_count()

1

##Putting tensors (and models) on the GPU
The reason we want our tensors/models on the GPU is because using a GPU results in faster computations.

In [ ]:
#Create a tensor (default on the CPU)
tensor = torch.tensor([1, 2, 3])

#Tensor not on GPU
print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [ ]:
#Move tensor to GPU (if available)
tensor_on_gpu = tensor.to(device)
tensor_on_gpu # 0 index of cuda, because we are using just one GPU

tensor([1, 2, 3], device='cuda:0')

##Moving tensors back to the CPU

In [ ]:
#If tensor is on GPU, can't transform it to NumPy
#NumPy doesn't work on GPU
#tensor_on_gpu.numpy()

In [ ]:
#To fix the GPU tensor with NumPy issues, we can first set it to the CPU
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu #because we have assigned it to different variable, tensor_on_gpu remains unchanged

array([1, 2, 3])